APPLICATION_NAME = "Ottopark"
APPLICATION_SLOGAN = ""
APPLICATION_DESCRIPTION = ""
APPLICATION_KEYWORDS = []
GENDERS = [["Homme"], ["Femme"]]
REGISTER_TYPES = [["Registre arrivée"], ["Registre départ"]]
POLL_STATUSES = [["En attente"], ["En cours"], ["Suspendu"], ["Terminé"], ["Annulé"]]
PRIORITIES = [["Aucun"],["Normal"], ["Basse"], ["Moyenne"], ["Haute"], ["Urgent"]]
TICKET_STATUSES = [["Nouveau"], ["En cours"], ["Résolu"], ["Fermé"], ["Rejeté"], ["En attente"]]
PERMISSION_ACTIONS = [["read"], ["create"], ["update"], ["destroy"]]
